language: node_js # 设置语言

node_js: stable # 设置相应版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - npm install hexo-cli -g

install:
    - npm install # 安装hexo及插件

script:
    - hexo clean # 清除
    - hexo g # 生成

after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - mv .deploy_git/google142c557f28c5c987.html ./public/
    - cd ./public
    - git config user.name "wenguang0816" # 修改name
    - git config user.email "2572880761@qq.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称

branches:
    only:
        - hexo #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置

env:
    global:
        - GH_REF: github.com/wenguang0816/wenguang0816.github.io.git #设置GH_REF，注意更改yourname